consumes:
- application/github.erebus+json
definitions: 
  task:
    type: object
    required:
      - period
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      status:
        type: string
        minLength: 1
        maxLength: 20
      repeats:
        type: integer
        format: int32
        readOnly: true
      date:
        type: string
        format: date-time
      period:
        type: string
        minLength: 1
      command:
        type: string
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
info:
  title: Erebus
  version: 0.1.0
paths: 
  /:
    get:
      tags:
        - tasks
      parameters:
        - name: status
          in: query
          type: string
          required: false
        - name: since
          in: query
          type: integer
          format: int64
          required: false
        - name: limit
          in: query
          type: integer
          format: int32
          required: false 
      responses:
        200:
          description: list the running tasks
          schema:
            type: array
            items:
              $ref: "#/definitions/task"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
produces:
- application/json
schemes:
- http
swagger: "2.0"
